services:
  dreamina:
    image: ghcr.io/gloryhry/dreamina-token-manager:latest
    container_name: dreamina-token-manager
    restart: always
    # Playwright/Chromium 在 Docker 中更稳定的共享内存配置
    shm_size: "1gb"
    ports:
      - "3000:3000"  # 主机:容器
    # 优先从 .env 读取环境变量，便于统一管理机密与配置
    env_file:
      - .env
    environment:
      # 如需修改对外端口，请同时调整上面的 ports 中主机端口
      SERVICE_PORT: "3000"
      # 其余配置（API_KEY、DATA_SAVE_MODE、REDIS_URL、LOG_LEVEL、ENABLE_FILE_LOG 等）
      # 推荐放入 .env 管理，这里无需重复定义
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:'+(process.env.SERVICE_PORT||3000), r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

# 使用说明：
# 1) 将 .env.example 复制为 .env 并按需修改变量（尤其是 API_KEY）。
# 2) 如需启用 Redis 模式：在 .env 设置 DATA_SAVE_MODE=redis 与 REDIS_URL=redis://<host>:6379。
# 3) 启动：docker compose -f docker-compose.yaml up -d
